//------------------------------------------------------------------------------
//
//                    Generated by VCL C++ .NET FrontEnd.
//                   (C)Copyright Boian Mitov 2005 - 2009
//                              www.mitov.com
//
//------------------------------------------------------------------------------
#ifndef CSLCommonGen_H_
#define CSLCommonGen_H_

//------------------------------------------------------------------------------
#ifndef VCLSupportH
  #include <VCLSupport.h>
#endif

#ifndef CSignalLabBasicPkgCB6_H_
  #include <CSignalLabBasicPkgCB6.h>
#endif
#ifndef CSLStreamTypes_H_
  #include <CSLStreamTypes.h>
#endif
#ifndef CSLFilterTypes_H_
  #include <CSLFilterTypes.h>
#endif
#ifndef CSLGenericFilterTypes_H_
  #include <CSLGenericFilterTypes.h>
#endif


//------------------------------------------------------------------------------


//------------------------------------------------------------------------------
class CTSLCommonGen : public CLPComponent
{
//DOM-IGNORE-BEGIN
  typedef CLPComponent inherited;
//DOM-IGNORE-END

  VCLHANDLE LibraryHandle;

protected:
  virtual TLPFunctionEntry  GetFunction( const char *function_name );

public:    // OpenWire Pins
  CTOWInputPinProperty EnablePin;
  CTOWInputPinProperty ClockPin;

public:    // Events
//  void __stdcall OnStart(VCLHANDLE Sender, double SampleRate);
  CLPEventProperty_2<1, void, VCLHANDLE, double> OnStart;
//  void __stdcall OnStop(VCLHANDLE Sender);
  CLPEventProperty_1<0, void, VCLHANDLE> OnStop;

public:    // Properties
  CLPProperty<bool> Enabled;
  CLPProperty<int> PumpPriority;
  CLPEnumProperty<CTSLClockSource> ClockSource;
  CLPProperty<int> BufferSize;
  CLPProperty<double> SampleRate;

public:
  virtual void Pump();
  void Start();
  void Stop();

public:
  CTSLCommonGen();
};
//------------------------------------------------------------------------------
class CTSLCommonBaseRealGen : public CTSLCommonGen
{
//DOM-IGNORE-BEGIN
  typedef CTSLCommonGen inherited;
//DOM-IGNORE-END

  VCLHANDLE LibraryHandle;

protected:
  virtual TLPFunctionEntry  GetFunction( const char *function_name );

public:
  CTSLCommonBaseRealGen();
};
//------------------------------------------------------------------------------
class CTSLCommonBlockGen : public CTSLCommonGen
{
//DOM-IGNORE-BEGIN
  typedef CTSLCommonGen inherited;
//DOM-IGNORE-END

  VCLHANDLE LibraryHandle;

protected:
  virtual TLPFunctionEntry  GetFunction( const char *function_name );

public:    // OpenWire Pins
  CTOWOutputPinProperty OutputPin;

public:
  virtual void Pump();

public:
  CTSLCommonBlockGen();
};
//------------------------------------------------------------------------------
class CTSLCommonComplexGen : public CTSLCommonGen
{
//DOM-IGNORE-BEGIN
  typedef CTSLCommonGen inherited;
//DOM-IGNORE-END

  VCLHANDLE LibraryHandle;

protected:
  virtual TLPFunctionEntry  GetFunction( const char *function_name );

public:    // OpenWire Pins
  CTOWOutputPinProperty OutputPin;

public:
  virtual void Pump();

public:
  CTSLCommonComplexGen();
};
//------------------------------------------------------------------------------
class CTSLCommonIntGen : public CTSLCommonGen
{
//DOM-IGNORE-BEGIN
  typedef CTSLCommonGen inherited;
//DOM-IGNORE-END

  VCLHANDLE LibraryHandle;

protected:
  virtual TLPFunctionEntry  GetFunction( const char *function_name );

public:    // OpenWire Pins
  CTOWOutputPinProperty OutputPin;

public:
  virtual void Pump();

public:
  CTSLCommonIntGen();
};
//------------------------------------------------------------------------------
class CTSLCommonRealGen : public CTSLCommonBaseRealGen
{
//DOM-IGNORE-BEGIN
  typedef CTSLCommonBaseRealGen inherited;
//DOM-IGNORE-END

  VCLHANDLE LibraryHandle;

protected:
  virtual TLPFunctionEntry  GetFunction( const char *function_name );

public:    // OpenWire Pins
  CTOWOutputPinProperty OutputPin;

public:
  virtual void Pump();

public:
  CTSLCommonRealGen();
};
//------------------------------------------------------------------------------
#include <CSLCommonGenCode.h>
//------------------------------------------------------------------------------
#endif   // CSLCommonGen_H_
//------------------------------------------------------------------------------
