//------------------------------------------------------------------------------
//
//                    Generated by VCL C++ .NET FrontEnd.
//                   (C)Copyright Boian Mitov 2005 - 2009
//                              www.mitov.com
//
//------------------------------------------------------------------------------
#ifndef CSLLevelDisplayCode_H_
#define CSLLevelDisplayCode_H_

//------------------------------------------------------------------------------
inline CTSLLevelDisplayColor::CTSLLevelDisplayColor( CLPBaseComponent *a_control, const CLPString a_PropertyName ) :
  inherited( a_control, a_PropertyName ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  Color( GetInstance(), _T( "Color" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLLevelDisplayColor::CTSLLevelDisplayColor( CLPClassProperty *a_property, const CLPString a_PropertyName ) :
  inherited( a_property, a_PropertyName ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  Color( GetInstance(), _T( "Color" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLLevelDisplayColor::CTSLLevelDisplayColor( CLPClassProperty *a_property, CTSLLevelDisplayColor ( CLPBaseClass::*a_getter )() ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(NULL),
  m_Owner_Property(a_property),
  Color( GetInstance(), _T( "Color" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLLevelDisplayColor::CTSLLevelDisplayColor( CLPClassProperty *a_property, CTSLLevelDisplayColor ( CLPBaseClass::*a_getter )(), void ( CLPBaseClass::*a_setter )( CTSLLevelDisplayColor ) ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_property),
  Color( GetInstance(), _T( "Color" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLLevelDisplayColor::CTSLLevelDisplayColor( CLPClassProperty *a_property, void ( CLPBaseClass::*a_setter )( CTSLLevelDisplayColor ) ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(NULL),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_property),
  Color( GetInstance(), _T( "Color" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLLevelDisplayColor::CTSLLevelDisplayColor( CLPBaseComponent *a_control, CTSLLevelDisplayColor ( CLPBaseClass::*a_getter )() ) :
  inherited( a_control, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(NULL),
  m_Owner_Property(a_control),
  Color( GetInstance(), _T( "Color" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLLevelDisplayColor::CTSLLevelDisplayColor( CLPBaseComponent *a_control, CTSLLevelDisplayColor ( CLPBaseClass::*a_getter )(), void ( CLPBaseClass::*a_setter )( CTSLLevelDisplayColor ) ) :
  inherited( a_control, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_control),
  Color( GetInstance(), _T( "Color" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLLevelDisplayColor::CTSLLevelDisplayColor( VCLHANDLE handle, ELPHandleMode owns_handle ) :
  inherited( handle, owns_handle ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  Color( GetInstance(), _T( "Color" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLLevelDisplayColor::CTSLLevelDisplayColor( const CTSLLevelDisplayColor &other ) :
  inherited( other ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  Color( GetInstance(), _T( "Color" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLLevelDisplayColor & CTSLLevelDisplayColor::operator = ( const CTSLLevelDisplayColor & other )
{
  if( m_Property_Setter )
	  (m_Owner_Property->*m_Property_Setter)( other );

  else
	  inherited::operator = ( other );

  return *this;
}
//------------------------------------------------------------------------------
inline VCLHANDLE CTSLLevelDisplayColor::Get_VCL_Handle() const
{
  if( m_Property_Getter )
	  {
		if( ! m_Object )
		  m_Object = new CVCLObject( (m_Owner_Property->*m_Property_Getter)().Get_VCL_Handle() );

	  }

  return inherited::Get_VCL_Handle();
}
//------------------------------------------------------------------------------
inline CTSLLevelDisplayColors::CTSLLevelDisplayColors( CLPBaseComponent *a_control, const CLPString a_PropertyName ) :
  inherited( a_control, a_PropertyName ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL )
{
}
//------------------------------------------------------------------------------
inline CTSLLevelDisplayColors::CTSLLevelDisplayColors( CLPClassProperty *a_property, const CLPString a_PropertyName ) :
  inherited( a_property, a_PropertyName ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL )
{
}
//------------------------------------------------------------------------------
inline CTSLLevelDisplayColors::CTSLLevelDisplayColors( CLPClassProperty *a_property, CTSLLevelDisplayColors ( CLPBaseClass::*a_getter )() ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(NULL),
  m_Owner_Property(a_property)
{
}
//------------------------------------------------------------------------------
inline CTSLLevelDisplayColors::CTSLLevelDisplayColors( CLPClassProperty *a_property, CTSLLevelDisplayColors ( CLPBaseClass::*a_getter )(), void ( CLPBaseClass::*a_setter )( CTSLLevelDisplayColors ) ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_property)
{
}
//------------------------------------------------------------------------------
inline CTSLLevelDisplayColors::CTSLLevelDisplayColors( CLPClassProperty *a_property, void ( CLPBaseClass::*a_setter )( CTSLLevelDisplayColors ) ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(NULL),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_property)
{
}
//------------------------------------------------------------------------------
inline CTSLLevelDisplayColors::CTSLLevelDisplayColors( CLPBaseComponent *a_control, CTSLLevelDisplayColors ( CLPBaseClass::*a_getter )() ) :
  inherited( a_control, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(NULL),
  m_Owner_Property(a_control)
{
}
//------------------------------------------------------------------------------
inline CTSLLevelDisplayColors::CTSLLevelDisplayColors( CLPBaseComponent *a_control, CTSLLevelDisplayColors ( CLPBaseClass::*a_getter )(), void ( CLPBaseClass::*a_setter )( CTSLLevelDisplayColors ) ) :
  inherited( a_control, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_control)
{
}
//------------------------------------------------------------------------------
inline CTSLLevelDisplayColors::CTSLLevelDisplayColors( VCLHANDLE handle, ELPHandleMode owns_handle ) :
  inherited( handle, owns_handle ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL )
{
}
//------------------------------------------------------------------------------
inline CTSLLevelDisplayColors::CTSLLevelDisplayColors( const CTSLLevelDisplayColors &other ) :
  inherited( other ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL )
{
}
//------------------------------------------------------------------------------
inline CTSLLevelDisplayColors & CTSLLevelDisplayColors::operator = ( const CTSLLevelDisplayColors & other )
{
  if( m_Property_Setter )
	  (m_Owner_Property->*m_Property_Setter)( other );

  else
	  inherited::operator = ( other );

  return *this;
}
//------------------------------------------------------------------------------
inline VCLHANDLE CTSLLevelDisplayColors::Get_VCL_Handle() const
{
  if( m_Property_Getter )
	  {
		if( ! m_Object )
		  m_Object = new CVCLObject( (m_Owner_Property->*m_Property_Getter)().Get_VCL_Handle() );

	  }

  return inherited::Get_VCL_Handle();
}
//------------------------------------------------------------------------------
inline CTSLBasicLevelAxis::CTSLBasicLevelAxis( CLPBaseComponent *a_control, const CLPString a_PropertyName ) :
  inherited( a_control, a_PropertyName ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  Color( GetInstance(), _T( "Color" ) ),
  Font( *new CTFont( GetInstance(), _T( "Font" ))),
  Precision( GetInstance(), _T( "Precision" ) ),
  FixedPrecision( GetInstance(), _T( "FixedPrecision" ) ),
  Visible( GetInstance(), _T( "Visible" ) ),
  ScaleMode( GetInstance(), _T( "ScaleMode" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLBasicLevelAxis::CTSLBasicLevelAxis( CLPClassProperty *a_property, const CLPString a_PropertyName ) :
  inherited( a_property, a_PropertyName ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  Color( GetInstance(), _T( "Color" ) ),
  Font( *new CTFont( GetInstance(), _T( "Font" ))),
  Precision( GetInstance(), _T( "Precision" ) ),
  FixedPrecision( GetInstance(), _T( "FixedPrecision" ) ),
  Visible( GetInstance(), _T( "Visible" ) ),
  ScaleMode( GetInstance(), _T( "ScaleMode" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLBasicLevelAxis::CTSLBasicLevelAxis( CLPClassProperty *a_property, CTSLBasicLevelAxis ( CLPBaseClass::*a_getter )() ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(NULL),
  m_Owner_Property(a_property),
  Color( GetInstance(), _T( "Color" ) ),
  Font( *new CTFont( GetInstance(), _T( "Font" ))),
  Precision( GetInstance(), _T( "Precision" ) ),
  FixedPrecision( GetInstance(), _T( "FixedPrecision" ) ),
  Visible( GetInstance(), _T( "Visible" ) ),
  ScaleMode( GetInstance(), _T( "ScaleMode" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLBasicLevelAxis::CTSLBasicLevelAxis( CLPClassProperty *a_property, CTSLBasicLevelAxis ( CLPBaseClass::*a_getter )(), void ( CLPBaseClass::*a_setter )( CTSLBasicLevelAxis ) ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_property),
  Color( GetInstance(), _T( "Color" ) ),
  Font( *new CTFont( GetInstance(), _T( "Font" ))),
  Precision( GetInstance(), _T( "Precision" ) ),
  FixedPrecision( GetInstance(), _T( "FixedPrecision" ) ),
  Visible( GetInstance(), _T( "Visible" ) ),
  ScaleMode( GetInstance(), _T( "ScaleMode" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLBasicLevelAxis::CTSLBasicLevelAxis( CLPClassProperty *a_property, void ( CLPBaseClass::*a_setter )( CTSLBasicLevelAxis ) ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(NULL),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_property),
  Color( GetInstance(), _T( "Color" ) ),
  Font( *new CTFont( GetInstance(), _T( "Font" ))),
  Precision( GetInstance(), _T( "Precision" ) ),
  FixedPrecision( GetInstance(), _T( "FixedPrecision" ) ),
  Visible( GetInstance(), _T( "Visible" ) ),
  ScaleMode( GetInstance(), _T( "ScaleMode" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLBasicLevelAxis::CTSLBasicLevelAxis( CLPBaseComponent *a_control, CTSLBasicLevelAxis ( CLPBaseClass::*a_getter )() ) :
  inherited( a_control, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(NULL),
  m_Owner_Property(a_control),
  Color( GetInstance(), _T( "Color" ) ),
  Font( *new CTFont( GetInstance(), _T( "Font" ))),
  Precision( GetInstance(), _T( "Precision" ) ),
  FixedPrecision( GetInstance(), _T( "FixedPrecision" ) ),
  Visible( GetInstance(), _T( "Visible" ) ),
  ScaleMode( GetInstance(), _T( "ScaleMode" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLBasicLevelAxis::CTSLBasicLevelAxis( CLPBaseComponent *a_control, CTSLBasicLevelAxis ( CLPBaseClass::*a_getter )(), void ( CLPBaseClass::*a_setter )( CTSLBasicLevelAxis ) ) :
  inherited( a_control, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_control),
  Color( GetInstance(), _T( "Color" ) ),
  Font( *new CTFont( GetInstance(), _T( "Font" ))),
  Precision( GetInstance(), _T( "Precision" ) ),
  FixedPrecision( GetInstance(), _T( "FixedPrecision" ) ),
  Visible( GetInstance(), _T( "Visible" ) ),
  ScaleMode( GetInstance(), _T( "ScaleMode" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLBasicLevelAxis::CTSLBasicLevelAxis( VCLHANDLE handle, ELPHandleMode owns_handle ) :
  inherited( handle, owns_handle ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  Color( GetInstance(), _T( "Color" ) ),
  Font( *new CTFont( GetInstance(), _T( "Font" ))),
  Precision( GetInstance(), _T( "Precision" ) ),
  FixedPrecision( GetInstance(), _T( "FixedPrecision" ) ),
  Visible( GetInstance(), _T( "Visible" ) ),
  ScaleMode( GetInstance(), _T( "ScaleMode" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLBasicLevelAxis::CTSLBasicLevelAxis( const CTSLBasicLevelAxis &other ) :
  inherited( other ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  Color( GetInstance(), _T( "Color" ) ),
  Font( *new CTFont( GetInstance(), _T( "Font" ))),
  Precision( GetInstance(), _T( "Precision" ) ),
  FixedPrecision( GetInstance(), _T( "FixedPrecision" ) ),
  Visible( GetInstance(), _T( "Visible" ) ),
  ScaleMode( GetInstance(), _T( "ScaleMode" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLBasicLevelAxis::~CTSLBasicLevelAxis()
{
  delete &Font;
}
//------------------------------------------------------------------------------
inline CTSLBasicLevelAxis & CTSLBasicLevelAxis::operator = ( const CTSLBasicLevelAxis & other )
{
  if( m_Property_Setter )
	  (m_Owner_Property->*m_Property_Setter)( other );

  else
	  inherited::operator = ( other );

  return *this;
}
//------------------------------------------------------------------------------
inline VCLHANDLE CTSLBasicLevelAxis::Get_VCL_Handle() const
{
  if( m_Property_Getter )
	  {
		if( ! m_Object )
		  m_Object = new CVCLObject( (m_Owner_Property->*m_Property_Getter)().Get_VCL_Handle() );

	  }

  return inherited::Get_VCL_Handle();
}
//------------------------------------------------------------------------------
inline CTSLLevelAxis::CTSLLevelAxis( CLPBaseComponent *a_control, const CLPString a_PropertyName ) :
  inherited( a_control, a_PropertyName ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  Autoscale( GetInstance(), _T( "Autoscale" ) ),
  Min( GetInstance(), _T( "Min" ) ),
  Max( GetInstance(), _T( "Max" ) ),
  OnCustomLabel( GetInstance(), _T( "OnCustomLabel" ) ),
  TickText( (CTSLLevelAxis *)GetInstance(), &CTSLLevelAxis::SetNewTickText)
{
}
//------------------------------------------------------------------------------
inline CTSLLevelAxis::CTSLLevelAxis( CLPClassProperty *a_property, const CLPString a_PropertyName ) :
  inherited( a_property, a_PropertyName ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  Autoscale( GetInstance(), _T( "Autoscale" ) ),
  Min( GetInstance(), _T( "Min" ) ),
  Max( GetInstance(), _T( "Max" ) ),
  OnCustomLabel( GetInstance(), _T( "OnCustomLabel" ) ),
  TickText( (CTSLLevelAxis *)GetInstance(), &CTSLLevelAxis::SetNewTickText)
{
}
//------------------------------------------------------------------------------
inline CTSLLevelAxis::CTSLLevelAxis( CLPClassProperty *a_property, CTSLLevelAxis ( CLPBaseClass::*a_getter )() ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(NULL),
  m_Owner_Property(a_property),
  Autoscale( GetInstance(), _T( "Autoscale" ) ),
  Min( GetInstance(), _T( "Min" ) ),
  Max( GetInstance(), _T( "Max" ) ),
  OnCustomLabel( GetInstance(), _T( "OnCustomLabel" ) ),
  TickText( (CTSLLevelAxis *)GetInstance(), &CTSLLevelAxis::SetNewTickText)
{
}
//------------------------------------------------------------------------------
inline CTSLLevelAxis::CTSLLevelAxis( CLPClassProperty *a_property, CTSLLevelAxis ( CLPBaseClass::*a_getter )(), void ( CLPBaseClass::*a_setter )( CTSLLevelAxis ) ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_property),
  Autoscale( GetInstance(), _T( "Autoscale" ) ),
  Min( GetInstance(), _T( "Min" ) ),
  Max( GetInstance(), _T( "Max" ) ),
  OnCustomLabel( GetInstance(), _T( "OnCustomLabel" ) ),
  TickText( (CTSLLevelAxis *)GetInstance(), &CTSLLevelAxis::SetNewTickText)
{
}
//------------------------------------------------------------------------------
inline CTSLLevelAxis::CTSLLevelAxis( CLPClassProperty *a_property, void ( CLPBaseClass::*a_setter )( CTSLLevelAxis ) ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(NULL),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_property),
  Autoscale( GetInstance(), _T( "Autoscale" ) ),
  Min( GetInstance(), _T( "Min" ) ),
  Max( GetInstance(), _T( "Max" ) ),
  OnCustomLabel( GetInstance(), _T( "OnCustomLabel" ) ),
  TickText( (CTSLLevelAxis *)GetInstance(), &CTSLLevelAxis::SetNewTickText)
{
}
//------------------------------------------------------------------------------
inline CTSLLevelAxis::CTSLLevelAxis( CLPBaseComponent *a_control, CTSLLevelAxis ( CLPBaseClass::*a_getter )() ) :
  inherited( a_control, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(NULL),
  m_Owner_Property(a_control),
  Autoscale( GetInstance(), _T( "Autoscale" ) ),
  Min( GetInstance(), _T( "Min" ) ),
  Max( GetInstance(), _T( "Max" ) ),
  OnCustomLabel( GetInstance(), _T( "OnCustomLabel" ) ),
  TickText( (CTSLLevelAxis *)GetInstance(), &CTSLLevelAxis::SetNewTickText)
{
}
//------------------------------------------------------------------------------
inline CTSLLevelAxis::CTSLLevelAxis( CLPBaseComponent *a_control, CTSLLevelAxis ( CLPBaseClass::*a_getter )(), void ( CLPBaseClass::*a_setter )( CTSLLevelAxis ) ) :
  inherited( a_control, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_control),
  Autoscale( GetInstance(), _T( "Autoscale" ) ),
  Min( GetInstance(), _T( "Min" ) ),
  Max( GetInstance(), _T( "Max" ) ),
  OnCustomLabel( GetInstance(), _T( "OnCustomLabel" ) ),
  TickText( (CTSLLevelAxis *)GetInstance(), &CTSLLevelAxis::SetNewTickText)
{
}
//------------------------------------------------------------------------------
inline CTSLLevelAxis::CTSLLevelAxis( VCLHANDLE handle, ELPHandleMode owns_handle ) :
  inherited( handle, owns_handle ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  Autoscale( GetInstance(), _T( "Autoscale" ) ),
  Min( GetInstance(), _T( "Min" ) ),
  Max( GetInstance(), _T( "Max" ) ),
  OnCustomLabel( GetInstance(), _T( "OnCustomLabel" ) ),
  TickText( (CTSLLevelAxis *)GetInstance(), &CTSLLevelAxis::SetNewTickText)
{
}
//------------------------------------------------------------------------------
inline CTSLLevelAxis::CTSLLevelAxis( const CTSLLevelAxis &other ) :
  inherited( other ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  Autoscale( GetInstance(), _T( "Autoscale" ) ),
  Min( GetInstance(), _T( "Min" ) ),
  Max( GetInstance(), _T( "Max" ) ),
  OnCustomLabel( GetInstance(), _T( "OnCustomLabel" ) ),
  TickText( (CTSLLevelAxis *)GetInstance(), &CTSLLevelAxis::SetNewTickText)
{
}
//------------------------------------------------------------------------------
inline CTSLLevelAxis & CTSLLevelAxis::operator = ( const CTSLLevelAxis & other )
{
  if( m_Property_Setter )
	  (m_Owner_Property->*m_Property_Setter)( other );

  else
	  inherited::operator = ( other );

  return *this;
}
//------------------------------------------------------------------------------
inline VCLHANDLE CTSLLevelAxis::Get_VCL_Handle() const
{
  if( m_Property_Getter )
	  {
		if( ! m_Object )
		  m_Object = new CVCLObject( (m_Owner_Property->*m_Property_Getter)().Get_VCL_Handle() );

	  }

  return inherited::Get_VCL_Handle();
}
//------------------------------------------------------------------------------
inline void CTSLLevelAxis::SetNewTickText( CTString Value )
{
  static void *__0_FuncPtr_ = NULL;
  if( __0_FuncPtr_ == NULL )
    __0_FuncPtr_ = (void *)( GetFunction( "@Slleveldisplay@TSLLevelAxis@SetNewTickText$qqr17System@AnsiString" ));

  VCLHANDLE __0_ThisPtr_ = Get_VCL_FunctionHandle();

  if( __0_FuncPtr_ && __0_ThisPtr_ )
    {
#ifdef USE_STD_STRING
    const char * __1_Param1 = Value.c_str();
#else
 #ifdef _UNICODE
    int __1_Length = Value.GetLength();
    char * __1_Param1 = new char[ __1_Length * 2 + 1 ];
    wchar_t * __1_wch_ = Value.LockBuffer();
  #if _MSC_VER >= 1400
    size_t   __1_i_;
    wcstombs_s( &__1_i_, __1_Param1, __1_Length * 2, __1_wch_, __1_Length );
  #else
    wcstombs( __1_Param1, __1_wch_, __1_Length );
  #endif
 #else
    char * __1_Param1 = Value.LockBuffer();
 #endif
#endif

    _asm
      {
      push eax
      push edx
      mov  edx,__1_Param1
      mov  eax,dword ptr [ __0_ThisPtr_ ]
      call dword ptr [ __0_FuncPtr_ ]
      pop  edx
      pop  eax
      }

#ifdef _UNICODE
    delete []__1_Param1;
#endif
#ifndef USE_STD_STRING
    Value.UnlockBuffer();
#endif
    }

}
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
inline CTSLBasicLevelDisplayLabel::CTSLBasicLevelDisplayLabel( CLPBaseComponent *a_control, const CLPString a_PropertyName ) :
  inherited( a_control, a_PropertyName ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL )
{
}
//------------------------------------------------------------------------------
inline CTSLBasicLevelDisplayLabel::CTSLBasicLevelDisplayLabel( CLPClassProperty *a_property, const CLPString a_PropertyName ) :
  inherited( a_property, a_PropertyName ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL )
{
}
//------------------------------------------------------------------------------
inline CTSLBasicLevelDisplayLabel::CTSLBasicLevelDisplayLabel( CLPClassProperty *a_property, CTSLBasicLevelDisplayLabel ( CLPBaseClass::*a_getter )() ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(NULL),
  m_Owner_Property(a_property)
{
}
//------------------------------------------------------------------------------
inline CTSLBasicLevelDisplayLabel::CTSLBasicLevelDisplayLabel( CLPClassProperty *a_property, CTSLBasicLevelDisplayLabel ( CLPBaseClass::*a_getter )(), void ( CLPBaseClass::*a_setter )( CTSLBasicLevelDisplayLabel ) ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_property)
{
}
//------------------------------------------------------------------------------
inline CTSLBasicLevelDisplayLabel::CTSLBasicLevelDisplayLabel( CLPClassProperty *a_property, void ( CLPBaseClass::*a_setter )( CTSLBasicLevelDisplayLabel ) ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(NULL),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_property)
{
}
//------------------------------------------------------------------------------
inline CTSLBasicLevelDisplayLabel::CTSLBasicLevelDisplayLabel( CLPBaseComponent *a_control, CTSLBasicLevelDisplayLabel ( CLPBaseClass::*a_getter )() ) :
  inherited( a_control, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(NULL),
  m_Owner_Property(a_control)
{
}
//------------------------------------------------------------------------------
inline CTSLBasicLevelDisplayLabel::CTSLBasicLevelDisplayLabel( CLPBaseComponent *a_control, CTSLBasicLevelDisplayLabel ( CLPBaseClass::*a_getter )(), void ( CLPBaseClass::*a_setter )( CTSLBasicLevelDisplayLabel ) ) :
  inherited( a_control, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_control)
{
}
//------------------------------------------------------------------------------
inline CTSLBasicLevelDisplayLabel::CTSLBasicLevelDisplayLabel( VCLHANDLE handle, ELPHandleMode owns_handle ) :
  inherited( handle, owns_handle ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL )
{
}
//------------------------------------------------------------------------------
inline CTSLBasicLevelDisplayLabel::CTSLBasicLevelDisplayLabel( const CTSLBasicLevelDisplayLabel &other ) :
  inherited( other ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL )
{
}
//------------------------------------------------------------------------------
inline CTSLBasicLevelDisplayLabel & CTSLBasicLevelDisplayLabel::operator = ( const CTSLBasicLevelDisplayLabel & other )
{
  if( m_Property_Setter )
	  (m_Owner_Property->*m_Property_Setter)( other );

  else
	  inherited::operator = ( other );

  return *this;
}
//------------------------------------------------------------------------------
inline VCLHANDLE CTSLBasicLevelDisplayLabel::Get_VCL_Handle() const
{
  if( m_Property_Getter )
	  {
		if( ! m_Object )
		  m_Object = new CVCLObject( (m_Owner_Property->*m_Property_Getter)().Get_VCL_Handle() );

	  }

  return inherited::Get_VCL_Handle();
}
//------------------------------------------------------------------------------
inline CTSLLevelDisplayLabel::CTSLLevelDisplayLabel( CLPBaseComponent *a_control, const CLPString a_PropertyName ) :
  inherited( a_control, a_PropertyName ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  Text( GetInstance(), _T( "Text" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLLevelDisplayLabel::CTSLLevelDisplayLabel( CLPClassProperty *a_property, const CLPString a_PropertyName ) :
  inherited( a_property, a_PropertyName ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  Text( GetInstance(), _T( "Text" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLLevelDisplayLabel::CTSLLevelDisplayLabel( CLPClassProperty *a_property, CTSLLevelDisplayLabel ( CLPBaseClass::*a_getter )() ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(NULL),
  m_Owner_Property(a_property),
  Text( GetInstance(), _T( "Text" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLLevelDisplayLabel::CTSLLevelDisplayLabel( CLPClassProperty *a_property, CTSLLevelDisplayLabel ( CLPBaseClass::*a_getter )(), void ( CLPBaseClass::*a_setter )( CTSLLevelDisplayLabel ) ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_property),
  Text( GetInstance(), _T( "Text" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLLevelDisplayLabel::CTSLLevelDisplayLabel( CLPClassProperty *a_property, void ( CLPBaseClass::*a_setter )( CTSLLevelDisplayLabel ) ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(NULL),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_property),
  Text( GetInstance(), _T( "Text" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLLevelDisplayLabel::CTSLLevelDisplayLabel( CLPBaseComponent *a_control, CTSLLevelDisplayLabel ( CLPBaseClass::*a_getter )() ) :
  inherited( a_control, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(NULL),
  m_Owner_Property(a_control),
  Text( GetInstance(), _T( "Text" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLLevelDisplayLabel::CTSLLevelDisplayLabel( CLPBaseComponent *a_control, CTSLLevelDisplayLabel ( CLPBaseClass::*a_getter )(), void ( CLPBaseClass::*a_setter )( CTSLLevelDisplayLabel ) ) :
  inherited( a_control, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_control),
  Text( GetInstance(), _T( "Text" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLLevelDisplayLabel::CTSLLevelDisplayLabel( VCLHANDLE handle, ELPHandleMode owns_handle ) :
  inherited( handle, owns_handle ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  Text( GetInstance(), _T( "Text" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLLevelDisplayLabel::CTSLLevelDisplayLabel( const CTSLLevelDisplayLabel &other ) :
  inherited( other ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  Text( GetInstance(), _T( "Text" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLLevelDisplayLabel & CTSLLevelDisplayLabel::operator = ( const CTSLLevelDisplayLabel & other )
{
  if( m_Property_Setter )
	  (m_Owner_Property->*m_Property_Setter)( other );

  else
	  inherited::operator = ( other );

  return *this;
}
//------------------------------------------------------------------------------
inline VCLHANDLE CTSLLevelDisplayLabel::Get_VCL_Handle() const
{
  if( m_Property_Getter )
	  {
		if( ! m_Object )
		  m_Object = new CVCLObject( (m_Owner_Property->*m_Property_Getter)().Get_VCL_Handle() );

	  }

  return inherited::Get_VCL_Handle();
}
//------------------------------------------------------------------------------
inline CTSLBasicLevelDisplayLevelView::CTSLBasicLevelDisplayLevelView( CLPBaseComponent *a_control, const CLPString a_PropertyName ) :
  inherited( a_control, a_PropertyName ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  BarWidth( GetInstance(), _T( "BarWidth" ) ),
  GrayScale( GetInstance(), _T( "GrayScale" ) ),
  Colors( *new CTSLLevelDisplayColors( GetInstance(), _T( "Colors" )))
{
}
//------------------------------------------------------------------------------
inline CTSLBasicLevelDisplayLevelView::CTSLBasicLevelDisplayLevelView( CLPClassProperty *a_property, const CLPString a_PropertyName ) :
  inherited( a_property, a_PropertyName ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  BarWidth( GetInstance(), _T( "BarWidth" ) ),
  GrayScale( GetInstance(), _T( "GrayScale" ) ),
  Colors( *new CTSLLevelDisplayColors( GetInstance(), _T( "Colors" )))
{
}
//------------------------------------------------------------------------------
inline CTSLBasicLevelDisplayLevelView::CTSLBasicLevelDisplayLevelView( CLPClassProperty *a_property, CTSLBasicLevelDisplayLevelView ( CLPBaseClass::*a_getter )() ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(NULL),
  m_Owner_Property(a_property),
  BarWidth( GetInstance(), _T( "BarWidth" ) ),
  GrayScale( GetInstance(), _T( "GrayScale" ) ),
  Colors( *new CTSLLevelDisplayColors( GetInstance(), _T( "Colors" )))
{
}
//------------------------------------------------------------------------------
inline CTSLBasicLevelDisplayLevelView::CTSLBasicLevelDisplayLevelView( CLPClassProperty *a_property, CTSLBasicLevelDisplayLevelView ( CLPBaseClass::*a_getter )(), void ( CLPBaseClass::*a_setter )( CTSLBasicLevelDisplayLevelView ) ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_property),
  BarWidth( GetInstance(), _T( "BarWidth" ) ),
  GrayScale( GetInstance(), _T( "GrayScale" ) ),
  Colors( *new CTSLLevelDisplayColors( GetInstance(), _T( "Colors" )))
{
}
//------------------------------------------------------------------------------
inline CTSLBasicLevelDisplayLevelView::CTSLBasicLevelDisplayLevelView( CLPClassProperty *a_property, void ( CLPBaseClass::*a_setter )( CTSLBasicLevelDisplayLevelView ) ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(NULL),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_property),
  BarWidth( GetInstance(), _T( "BarWidth" ) ),
  GrayScale( GetInstance(), _T( "GrayScale" ) ),
  Colors( *new CTSLLevelDisplayColors( GetInstance(), _T( "Colors" )))
{
}
//------------------------------------------------------------------------------
inline CTSLBasicLevelDisplayLevelView::CTSLBasicLevelDisplayLevelView( CLPBaseComponent *a_control, CTSLBasicLevelDisplayLevelView ( CLPBaseClass::*a_getter )() ) :
  inherited( a_control, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(NULL),
  m_Owner_Property(a_control),
  BarWidth( GetInstance(), _T( "BarWidth" ) ),
  GrayScale( GetInstance(), _T( "GrayScale" ) ),
  Colors( *new CTSLLevelDisplayColors( GetInstance(), _T( "Colors" )))
{
}
//------------------------------------------------------------------------------
inline CTSLBasicLevelDisplayLevelView::CTSLBasicLevelDisplayLevelView( CLPBaseComponent *a_control, CTSLBasicLevelDisplayLevelView ( CLPBaseClass::*a_getter )(), void ( CLPBaseClass::*a_setter )( CTSLBasicLevelDisplayLevelView ) ) :
  inherited( a_control, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_control),
  BarWidth( GetInstance(), _T( "BarWidth" ) ),
  GrayScale( GetInstance(), _T( "GrayScale" ) ),
  Colors( *new CTSLLevelDisplayColors( GetInstance(), _T( "Colors" )))
{
}
//------------------------------------------------------------------------------
inline CTSLBasicLevelDisplayLevelView::CTSLBasicLevelDisplayLevelView( VCLHANDLE handle, ELPHandleMode owns_handle ) :
  inherited( handle, owns_handle ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  BarWidth( GetInstance(), _T( "BarWidth" ) ),
  GrayScale( GetInstance(), _T( "GrayScale" ) ),
  Colors( *new CTSLLevelDisplayColors( GetInstance(), _T( "Colors" )))
{
}
//------------------------------------------------------------------------------
inline CTSLBasicLevelDisplayLevelView::CTSLBasicLevelDisplayLevelView( const CTSLBasicLevelDisplayLevelView &other ) :
  inherited( other ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  BarWidth( GetInstance(), _T( "BarWidth" ) ),
  GrayScale( GetInstance(), _T( "GrayScale" ) ),
  Colors( *new CTSLLevelDisplayColors( GetInstance(), _T( "Colors" )))
{
}
//------------------------------------------------------------------------------
inline CTSLBasicLevelDisplayLevelView::~CTSLBasicLevelDisplayLevelView()
{
  delete &Colors;
}
//------------------------------------------------------------------------------
inline CTSLBasicLevelDisplayLevelView & CTSLBasicLevelDisplayLevelView::operator = ( const CTSLBasicLevelDisplayLevelView & other )
{
  if( m_Property_Setter )
	  (m_Owner_Property->*m_Property_Setter)( other );

  else
	  inherited::operator = ( other );

  return *this;
}
//------------------------------------------------------------------------------
inline VCLHANDLE CTSLBasicLevelDisplayLevelView::Get_VCL_Handle() const
{
  if( m_Property_Getter )
	  {
		if( ! m_Object )
		  m_Object = new CVCLObject( (m_Owner_Property->*m_Property_Getter)().Get_VCL_Handle() );

	  }

  return inherited::Get_VCL_Handle();
}
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
inline CTSLAxisDisplayLevelView::CTSLAxisDisplayLevelView( CLPBaseComponent *a_control, const CLPString a_PropertyName ) :
  inherited( a_control, a_PropertyName ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  Axis( *new CTSLLevelAxis( GetInstance(), _T( "Axis" )))
{
}
//------------------------------------------------------------------------------
inline CTSLAxisDisplayLevelView::CTSLAxisDisplayLevelView( CLPClassProperty *a_property, const CLPString a_PropertyName ) :
  inherited( a_property, a_PropertyName ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  Axis( *new CTSLLevelAxis( GetInstance(), _T( "Axis" )))
{
}
//------------------------------------------------------------------------------
inline CTSLAxisDisplayLevelView::CTSLAxisDisplayLevelView( CLPClassProperty *a_property, CTSLAxisDisplayLevelView ( CLPBaseClass::*a_getter )() ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(NULL),
  m_Owner_Property(a_property),
  Axis( *new CTSLLevelAxis( GetInstance(), _T( "Axis" )))
{
}
//------------------------------------------------------------------------------
inline CTSLAxisDisplayLevelView::CTSLAxisDisplayLevelView( CLPClassProperty *a_property, CTSLAxisDisplayLevelView ( CLPBaseClass::*a_getter )(), void ( CLPBaseClass::*a_setter )( CTSLAxisDisplayLevelView ) ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_property),
  Axis( *new CTSLLevelAxis( GetInstance(), _T( "Axis" )))
{
}
//------------------------------------------------------------------------------
inline CTSLAxisDisplayLevelView::CTSLAxisDisplayLevelView( CLPClassProperty *a_property, void ( CLPBaseClass::*a_setter )( CTSLAxisDisplayLevelView ) ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(NULL),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_property),
  Axis( *new CTSLLevelAxis( GetInstance(), _T( "Axis" )))
{
}
//------------------------------------------------------------------------------
inline CTSLAxisDisplayLevelView::CTSLAxisDisplayLevelView( CLPBaseComponent *a_control, CTSLAxisDisplayLevelView ( CLPBaseClass::*a_getter )() ) :
  inherited( a_control, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(NULL),
  m_Owner_Property(a_control),
  Axis( *new CTSLLevelAxis( GetInstance(), _T( "Axis" )))
{
}
//------------------------------------------------------------------------------
inline CTSLAxisDisplayLevelView::CTSLAxisDisplayLevelView( CLPBaseComponent *a_control, CTSLAxisDisplayLevelView ( CLPBaseClass::*a_getter )(), void ( CLPBaseClass::*a_setter )( CTSLAxisDisplayLevelView ) ) :
  inherited( a_control, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_control),
  Axis( *new CTSLLevelAxis( GetInstance(), _T( "Axis" )))
{
}
//------------------------------------------------------------------------------
inline CTSLAxisDisplayLevelView::CTSLAxisDisplayLevelView( VCLHANDLE handle, ELPHandleMode owns_handle ) :
  inherited( handle, owns_handle ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  Axis( *new CTSLLevelAxis( GetInstance(), _T( "Axis" )))
{
}
//------------------------------------------------------------------------------
inline CTSLAxisDisplayLevelView::CTSLAxisDisplayLevelView( const CTSLAxisDisplayLevelView &other ) :
  inherited( other ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  Axis( *new CTSLLevelAxis( GetInstance(), _T( "Axis" )))
{
}
//------------------------------------------------------------------------------
inline CTSLAxisDisplayLevelView::~CTSLAxisDisplayLevelView()
{
  delete &Axis;
}
//------------------------------------------------------------------------------
inline CTSLAxisDisplayLevelView & CTSLAxisDisplayLevelView::operator = ( const CTSLAxisDisplayLevelView & other )
{
  if( m_Property_Setter )
	  (m_Owner_Property->*m_Property_Setter)( other );

  else
	  inherited::operator = ( other );

  return *this;
}
//------------------------------------------------------------------------------
inline VCLHANDLE CTSLAxisDisplayLevelView::Get_VCL_Handle() const
{
  if( m_Property_Getter )
	  {
		if( ! m_Object )
		  m_Object = new CVCLObject( (m_Owner_Property->*m_Property_Getter)().Get_VCL_Handle() );

	  }

  return inherited::Get_VCL_Handle();
}
//------------------------------------------------------------------------------
inline CTSLDisplayLevelView::CTSLDisplayLevelView( CLPBaseComponent *a_control, const CLPString a_PropertyName ) :
  inherited( a_control, a_PropertyName ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  LevelLabel( *new CTSLLevelDisplayLabel( GetInstance(), ( CTSLLevelDisplayLabel ( CLPBaseClass::* )() ) &::CTSLDisplayLevelView::GetLevelLabel, ( void ( CLPBaseClass::* )( CTSLLevelDisplayLabel ) ) &::CTSLDisplayLevelView::SetLevelLabel ))
{
}
//------------------------------------------------------------------------------
inline CTSLDisplayLevelView::CTSLDisplayLevelView( CLPClassProperty *a_property, const CLPString a_PropertyName ) :
  inherited( a_property, a_PropertyName ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  LevelLabel( *new CTSLLevelDisplayLabel( GetInstance(), ( CTSLLevelDisplayLabel ( CLPBaseClass::* )() ) &::CTSLDisplayLevelView::GetLevelLabel, ( void ( CLPBaseClass::* )( CTSLLevelDisplayLabel ) ) &::CTSLDisplayLevelView::SetLevelLabel ))
{
}
//------------------------------------------------------------------------------
inline CTSLDisplayLevelView::CTSLDisplayLevelView( CLPClassProperty *a_property, CTSLDisplayLevelView ( CLPBaseClass::*a_getter )() ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(NULL),
  m_Owner_Property(a_property),
  LevelLabel( *new CTSLLevelDisplayLabel( GetInstance(), ( CTSLLevelDisplayLabel ( CLPBaseClass::* )() ) &::CTSLDisplayLevelView::GetLevelLabel, ( void ( CLPBaseClass::* )( CTSLLevelDisplayLabel ) ) &::CTSLDisplayLevelView::SetLevelLabel ))
{
}
//------------------------------------------------------------------------------
inline CTSLDisplayLevelView::CTSLDisplayLevelView( CLPClassProperty *a_property, CTSLDisplayLevelView ( CLPBaseClass::*a_getter )(), void ( CLPBaseClass::*a_setter )( CTSLDisplayLevelView ) ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_property),
  LevelLabel( *new CTSLLevelDisplayLabel( GetInstance(), ( CTSLLevelDisplayLabel ( CLPBaseClass::* )() ) &::CTSLDisplayLevelView::GetLevelLabel, ( void ( CLPBaseClass::* )( CTSLLevelDisplayLabel ) ) &::CTSLDisplayLevelView::SetLevelLabel ))
{
}
//------------------------------------------------------------------------------
inline CTSLDisplayLevelView::CTSLDisplayLevelView( CLPClassProperty *a_property, void ( CLPBaseClass::*a_setter )( CTSLDisplayLevelView ) ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(NULL),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_property),
  LevelLabel( *new CTSLLevelDisplayLabel( GetInstance(), ( CTSLLevelDisplayLabel ( CLPBaseClass::* )() ) &::CTSLDisplayLevelView::GetLevelLabel, ( void ( CLPBaseClass::* )( CTSLLevelDisplayLabel ) ) &::CTSLDisplayLevelView::SetLevelLabel ))
{
}
//------------------------------------------------------------------------------
inline CTSLDisplayLevelView::CTSLDisplayLevelView( CLPBaseComponent *a_control, CTSLDisplayLevelView ( CLPBaseClass::*a_getter )() ) :
  inherited( a_control, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(NULL),
  m_Owner_Property(a_control),
  LevelLabel( *new CTSLLevelDisplayLabel( GetInstance(), ( CTSLLevelDisplayLabel ( CLPBaseClass::* )() ) &::CTSLDisplayLevelView::GetLevelLabel, ( void ( CLPBaseClass::* )( CTSLLevelDisplayLabel ) ) &::CTSLDisplayLevelView::SetLevelLabel ))
{
}
//------------------------------------------------------------------------------
inline CTSLDisplayLevelView::CTSLDisplayLevelView( CLPBaseComponent *a_control, CTSLDisplayLevelView ( CLPBaseClass::*a_getter )(), void ( CLPBaseClass::*a_setter )( CTSLDisplayLevelView ) ) :
  inherited( a_control, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_control),
  LevelLabel( *new CTSLLevelDisplayLabel( GetInstance(), ( CTSLLevelDisplayLabel ( CLPBaseClass::* )() ) &::CTSLDisplayLevelView::GetLevelLabel, ( void ( CLPBaseClass::* )( CTSLLevelDisplayLabel ) ) &::CTSLDisplayLevelView::SetLevelLabel ))
{
}
//------------------------------------------------------------------------------
inline CTSLDisplayLevelView::CTSLDisplayLevelView( VCLHANDLE handle, ELPHandleMode owns_handle ) :
  inherited( handle, owns_handle ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  LevelLabel( *new CTSLLevelDisplayLabel( GetInstance(), ( CTSLLevelDisplayLabel ( CLPBaseClass::* )() ) &::CTSLDisplayLevelView::GetLevelLabel, ( void ( CLPBaseClass::* )( CTSLLevelDisplayLabel ) ) &::CTSLDisplayLevelView::SetLevelLabel ))
{
}
//------------------------------------------------------------------------------
inline CTSLDisplayLevelView::CTSLDisplayLevelView( const CTSLDisplayLevelView &other ) :
  inherited( other ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  LevelLabel( *new CTSLLevelDisplayLabel( GetInstance(), ( CTSLLevelDisplayLabel ( CLPBaseClass::* )() ) &::CTSLDisplayLevelView::GetLevelLabel, ( void ( CLPBaseClass::* )( CTSLLevelDisplayLabel ) ) &::CTSLDisplayLevelView::SetLevelLabel ))
{
}
//------------------------------------------------------------------------------
inline CTSLDisplayLevelView::~CTSLDisplayLevelView()
{
  delete &LevelLabel;
}
//------------------------------------------------------------------------------
inline CTSLDisplayLevelView & CTSLDisplayLevelView::operator = ( const CTSLDisplayLevelView & other )
{
  if( m_Property_Setter )
	  (m_Owner_Property->*m_Property_Setter)( other );

  else
	  inherited::operator = ( other );

  return *this;
}
//------------------------------------------------------------------------------
inline VCLHANDLE CTSLDisplayLevelView::Get_VCL_Handle() const
{
  if( m_Property_Getter )
	  {
		if( ! m_Object )
		  m_Object = new CVCLObject( (m_Owner_Property->*m_Property_Getter)().Get_VCL_Handle() );

	  }

  return inherited::Get_VCL_Handle();
}
//------------------------------------------------------------------------------
inline CTSLLevelDisplayLabel CTSLDisplayLevelView::GetLevelLabel()
{
  static void *__0_FuncPtr_ = NULL;
  if( __0_FuncPtr_ == NULL )
    __0_FuncPtr_ = (void *)( GetFunction( "@Slleveldisplay@TSLDisplayLevelView@GetLevelLabel$qqrv" ));

  VCLHANDLE __0_ThisPtr_ = Get_VCL_FunctionHandle();

  VCLHANDLE __0_RtnValue_ = NULL;

  if( __0_FuncPtr_ && __0_ThisPtr_ )
    {
    _asm
      {
      push eax
      mov  eax,dword ptr [ __0_ThisPtr_ ]
      call dword ptr [ __0_FuncPtr_ ]
      mov  __0_RtnValue_,eax
      pop  eax
      }
    }

  return (CTSLLevelDisplayLabel)__0_RtnValue_;
}
//------------------------------------------------------------------------------
inline void CTSLDisplayLevelView::SetLevelLabel( CTSLLevelDisplayLabel AValue )
{
  static void *__0_FuncPtr_ = NULL;
  if( __0_FuncPtr_ == NULL )
    __0_FuncPtr_ = (void *)( GetFunction( "@Slleveldisplay@TSLDisplayLevelView@SetLevelLabel$qqrp35Slleveldisplay@TSLLevelDisplayLabel" ));

  VCLHANDLE __0_ThisPtr_ = Get_VCL_FunctionHandle();

  if( __0_FuncPtr_ && __0_ThisPtr_ )
    {
    VCLHANDLE __1_Param1 = AValue.GetInternalHandle();

    _asm
      {
      push eax
      push edx
      mov  edx,__1_Param1
      mov  eax,dword ptr [ __0_ThisPtr_ ]
      call dword ptr [ __0_FuncPtr_ ]
      pop  edx
      pop  eax
      }
    }

}
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
#endif   // CSLLevelDisplayCode_H_
//------------------------------------------------------------------------------
