//------------------------------------------------------------------------------
//
//                    Generated by VCL C++ .NET FrontEnd.
//                   (C)Copyright Boian Mitov 2005 - 2009
//                              www.mitov.com
//
//------------------------------------------------------------------------------
#ifndef CSLMultiInputCode_H_
#define CSLMultiInputCode_H_

//------------------------------------------------------------------------------
inline CTSLMultiInput::CTSLMultiInput() :
  BufferSize( GetInstance(), _T( "BufferSize" ) )
{
  LibraryHandle = VCL_LoadLibrary( "SignalLabBasicPkgCB6.bpl" );
}
//------------------------------------------------------------------------------
inline TLPFunctionEntry CTSLMultiInput::GetFunction( const char *function_name )
{
  TLPFunctionEntry Result = VCL_GetFunction( LibraryHandle, function_name );
  if( Result )
    return Result;

  return inherited::GetFunction( function_name );
}
//------------------------------------------------------------------------------
inline CTSLRealMultiInput::CTSLRealMultiInput() :
  OutputPin( GetInstance(), _T( "OutputPin" ) )
{
  LibraryHandle = VCL_LoadLibrary( "SignalLabBasicPkgCB6.bpl" );
}
//------------------------------------------------------------------------------
inline TLPFunctionEntry CTSLRealMultiInput::GetFunction( const char *function_name )
{
  TLPFunctionEntry Result = VCL_GetFunction( LibraryHandle, function_name );
  if( Result )
    return Result;

  return inherited::GetFunction( function_name );
}
//------------------------------------------------------------------------------
#endif   // CSLMultiInputCode_H_
//------------------------------------------------------------------------------
