//------------------------------------------------------------------------------
//
//                    Generated by VCL C++ .NET FrontEnd.
//                   (C)Copyright Boian Mitov 2005 - 2009
//                              www.mitov.com
//
//------------------------------------------------------------------------------
#ifndef CSLWindowFilter_H_
#define CSLWindowFilter_H_

//------------------------------------------------------------------------------
#ifndef VCLSupportH
  #include <VCLSupport.h>
#endif

#ifndef CSignalLabBasicPkgCB6_H_
  #include <CSignalLabBasicPkgCB6.h>
#endif
#ifndef CSLFilterTypes_H_
  #include <CSLFilterTypes.h>
#endif


//------------------------------------------------------------------------------


//------------------------------------------------------------------------------
#include <CSLWindowFilterCode.h>
//------------------------------------------------------------------------------
#endif   // CSLWindowFilter_H_
//------------------------------------------------------------------------------
