-- megafunction wizard: %LPM_BUSTRI%
-- GENERATION: STANDARD
-- VERSION: WM1.0
-- MODULE: lpm_bustri 

-- ============================================================
-- File Name: tri_sdio.vhd
-- Megafunction Name(s):
--          lpm_bustri
--
-- Simulation Library Files(s):
--          lpm
-- ============================================================
-- ************************************************************
-- THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
--
-- 8.0 Build 231 07/10/2008 SP 1 SJ Full Version
-- ************************************************************


--Copyright (C) 1991-2008 Altera Corporation
--Your use of Altera Corporation's design tools, logic functions 
--and other software and tools, and its AMPP partner logic 
--functions, and any output files from any of the foregoing 
--(including device programming or simulation files), and any 
--associated documentation or information are expressly subject 
--to the terms and conditions of the Altera Program License 
--Subscription Agreement, Altera MegaCore Function License 
--Agreement, or other applicable license agreement, including, 
--without limitation, that your use is for the sole purpose of 
--programming logic devices manufactured by Altera and sold by 
--Altera or its authorized distributors.  Please refer to the 
--applicable agreement for further details.


library ieee;
use ieee.std_logic_1164.all;

library lpm;
use lpm.all;

entity tri_sdio is
    port (
        data     : in    std_logic;
        enabledt : in    std_logic;
        enabletr : in    std_logic;
        result   : out   std_logic;
        tridata  : inout std_logic_vector (0 downto 0)
        );
end tri_sdio;


architecture SYN of tri_sdio is

    signal sub_wire0 : std_logic_vector (0 downto 0);
    signal sub_wire1 : std_logic;
    signal sub_wire2 : std_logic;
    signal sub_wire3 : std_logic_vector (0 downto 0);



    component lpm_bustri
        generic (
            lpm_type  : string;
            lpm_width : natural
            );
        port (
            enabletr : in    std_logic;
            enabledt : in    std_logic;
            data     : in    std_logic_vector (0 downto 0);
            result   : out   std_logic_vector (0 downto 0);
            tridata  : inout std_logic_vector (0 downto 0)
            );
    end component;

begin
    sub_wire1    <= sub_wire0(0);
    result       <= sub_wire1;
    sub_wire2    <= data;
    sub_wire3(0) <= sub_wire2;

    lpm_bustri_component : lpm_bustri
        generic map (
            lpm_type  => "LPM_BUSTRI",
            lpm_width => 1
            )
        port map (
            enabletr => enabletr,
            enabledt => enabledt,
            data     => sub_wire3,
            result   => sub_wire0,
            tridata  => tridata
            );



end SYN;

-- ============================================================
-- CNX file retrieval info
-- ============================================================
-- Retrieval info: PRIVATE: BiDir NUMERIC "1"
-- Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Stratix II"
-- Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "0"
-- Retrieval info: PRIVATE: nBit NUMERIC "1"
-- Retrieval info: CONSTANT: LPM_TYPE STRING "LPM_BUSTRI"
-- Retrieval info: CONSTANT: LPM_WIDTH NUMERIC "1"
-- Retrieval info: USED_PORT: data 0 0 0 0 INPUT NODEFVAL data
-- Retrieval info: USED_PORT: enabledt 0 0 0 0 INPUT NODEFVAL enabledt
-- Retrieval info: USED_PORT: enabletr 0 0 0 0 INPUT NODEFVAL enabletr
-- Retrieval info: USED_PORT: result 0 0 0 0 OUTPUT NODEFVAL result
-- Retrieval info: USED_PORT: tridata 0 0 1 0 BIDIR NODEFVAL tridata[0..0]
-- Retrieval info: CONNECT: tridata 0 0 1 0 @tridata 0 0 1 0
-- Retrieval info: CONNECT: @data 0 0 1 0 data 0 0 0 0
-- Retrieval info: CONNECT: @enabledt 0 0 0 0 enabledt 0 0 0 0
-- Retrieval info: CONNECT: result 0 0 0 0 @result 0 0 1 0
-- Retrieval info: CONNECT: @enabletr 0 0 0 0 enabletr 0 0 0 0
-- Retrieval info: LIBRARY: lpm lpm.lpm_components.all
-- Retrieval info: GEN_FILE: TYPE_NORMAL tri_sdio.vhd TRUE
-- Retrieval info: GEN_FILE: TYPE_NORMAL tri_sdio.inc FALSE
-- Retrieval info: GEN_FILE: TYPE_NORMAL tri_sdio.cmp FALSE
-- Retrieval info: GEN_FILE: TYPE_NORMAL tri_sdio.bsf TRUE
-- Retrieval info: GEN_FILE: TYPE_NORMAL tri_sdio_inst.vhd FALSE
-- Retrieval info: LIB_FILE: lpm
