//------------------------------------------------------------------------------
//
//                    Generated by VCL C++ .NET FrontEnd.
//                   (C)Copyright Boian Mitov 2005 - 2009
//                              www.mitov.com
//
//------------------------------------------------------------------------------
#ifndef CSLCommonGenCode_H_
#define CSLCommonGenCode_H_

//------------------------------------------------------------------------------
inline CTSLCommonGen::CTSLCommonGen() :
  EnablePin( GetInstance(), _T( "EnablePin" ) ),
  ClockPin( GetInstance(), _T( "ClockPin" ) ),
  Enabled( GetInstance(), _T( "Enabled" ) ),
  PumpPriority( GetInstance(), _T( "PumpPriority" ) ),
  ClockSource( GetInstance(), _T( "ClockSource" ) ),
  BufferSize( GetInstance(), _T( "BufferSize" ) ),
  SampleRate( GetInstance(), _T( "SampleRate" ) ),
  OnStart( GetInstance(), _T( "OnStart" ) ),
  OnStop( GetInstance(), _T( "OnStop" ) )
{
  LibraryHandle = VCL_LoadLibrary( "SignalLabBasicPkgCB6.bpl" );
}
//------------------------------------------------------------------------------
inline TLPFunctionEntry CTSLCommonGen::GetFunction( const char *function_name )
{
  TLPFunctionEntry Result = VCL_GetFunction( LibraryHandle, function_name );
  if( Result )
    return Result;

  return inherited::GetFunction( function_name );
}
//------------------------------------------------------------------------------
inline void CTSLCommonGen::Pump()
{
  static void *__0_FuncPtr_ = NULL;
  if( __0_FuncPtr_ == NULL )
    __0_FuncPtr_ = (void *)( GetFunction( "@Slcommongen@TSLCommonGen@Pump$qqrv" ));

  VCLHANDLE __0_ThisPtr_ = Get_VCL_FunctionHandle();

  if( __0_FuncPtr_ && __0_ThisPtr_ )
    {
    _asm
      {
      push eax
      mov  eax,dword ptr [ __0_ThisPtr_ ]
      call dword ptr [ __0_FuncPtr_ ]
      pop  eax
      }
    }

}
//------------------------------------------------------------------------------
inline void CTSLCommonGen::Start()
{
  static void *__0_FuncPtr_ = NULL;
  if( __0_FuncPtr_ == NULL )
    __0_FuncPtr_ = (void *)( GetFunction( "@Slcommongen@TSLCommonGen@Start$qqrv" ));

  VCLHANDLE __0_ThisPtr_ = Get_VCL_FunctionHandle();

  if( __0_FuncPtr_ && __0_ThisPtr_ )
    {
    _asm
      {
      push eax
      mov  eax,dword ptr [ __0_ThisPtr_ ]
      call dword ptr [ __0_FuncPtr_ ]
      pop  eax
      }
    }

}
//------------------------------------------------------------------------------
inline void CTSLCommonGen::Stop()
{
  static void *__0_FuncPtr_ = NULL;
  if( __0_FuncPtr_ == NULL )
    __0_FuncPtr_ = (void *)( GetFunction( "@Slcommongen@TSLCommonGen@Stop$qqrv" ));

  VCLHANDLE __0_ThisPtr_ = Get_VCL_FunctionHandle();

  if( __0_FuncPtr_ && __0_ThisPtr_ )
    {
    _asm
      {
      push eax
      mov  eax,dword ptr [ __0_ThisPtr_ ]
      call dword ptr [ __0_FuncPtr_ ]
      pop  eax
      }
    }

}
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
inline CTSLCommonBaseRealGen::CTSLCommonBaseRealGen()
{
  LibraryHandle = VCL_LoadLibrary( "SignalLabBasicPkgCB6.bpl" );
}
//------------------------------------------------------------------------------
inline TLPFunctionEntry CTSLCommonBaseRealGen::GetFunction( const char *function_name )
{
  TLPFunctionEntry Result = VCL_GetFunction( LibraryHandle, function_name );
  if( Result )
    return Result;

  return inherited::GetFunction( function_name );
}
//------------------------------------------------------------------------------
inline CTSLCommonBlockGen::CTSLCommonBlockGen() :
  OutputPin( GetInstance(), _T( "OutputPin" ) )
{
  LibraryHandle = VCL_LoadLibrary( "SignalLabBasicPkgCB6.bpl" );
}
//------------------------------------------------------------------------------
inline TLPFunctionEntry CTSLCommonBlockGen::GetFunction( const char *function_name )
{
  TLPFunctionEntry Result = VCL_GetFunction( LibraryHandle, function_name );
  if( Result )
    return Result;

  return inherited::GetFunction( function_name );
}
//------------------------------------------------------------------------------
inline void CTSLCommonBlockGen::Pump()
{
  static void *__0_FuncPtr_ = NULL;
  if( __0_FuncPtr_ == NULL )
    __0_FuncPtr_ = (void *)( GetFunction( "@Slcommongen@TSLCommonBlockGen@Pump$qqrv" ));

  VCLHANDLE __0_ThisPtr_ = Get_VCL_FunctionHandle();

  if( __0_FuncPtr_ && __0_ThisPtr_ )
    {
    _asm
      {
      push eax
      mov  eax,dword ptr [ __0_ThisPtr_ ]
      call dword ptr [ __0_FuncPtr_ ]
      pop  eax
      }
    }

}
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
inline CTSLCommonComplexGen::CTSLCommonComplexGen() :
  OutputPin( GetInstance(), _T( "OutputPin" ) )
{
  LibraryHandle = VCL_LoadLibrary( "SignalLabBasicPkgCB6.bpl" );
}
//------------------------------------------------------------------------------
inline TLPFunctionEntry CTSLCommonComplexGen::GetFunction( const char *function_name )
{
  TLPFunctionEntry Result = VCL_GetFunction( LibraryHandle, function_name );
  if( Result )
    return Result;

  return inherited::GetFunction( function_name );
}
//------------------------------------------------------------------------------
inline void CTSLCommonComplexGen::Pump()
{
  static void *__0_FuncPtr_ = NULL;
  if( __0_FuncPtr_ == NULL )
    __0_FuncPtr_ = (void *)( GetFunction( "@Slcommongen@TSLCommonComplexGen@Pump$qqrv" ));

  VCLHANDLE __0_ThisPtr_ = Get_VCL_FunctionHandle();

  if( __0_FuncPtr_ && __0_ThisPtr_ )
    {
    _asm
      {
      push eax
      mov  eax,dword ptr [ __0_ThisPtr_ ]
      call dword ptr [ __0_FuncPtr_ ]
      pop  eax
      }
    }

}
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
inline CTSLCommonIntGen::CTSLCommonIntGen() :
  OutputPin( GetInstance(), _T( "OutputPin" ) )
{
  LibraryHandle = VCL_LoadLibrary( "SignalLabBasicPkgCB6.bpl" );
}
//------------------------------------------------------------------------------
inline TLPFunctionEntry CTSLCommonIntGen::GetFunction( const char *function_name )
{
  TLPFunctionEntry Result = VCL_GetFunction( LibraryHandle, function_name );
  if( Result )
    return Result;

  return inherited::GetFunction( function_name );
}
//------------------------------------------------------------------------------
inline void CTSLCommonIntGen::Pump()
{
  static void *__0_FuncPtr_ = NULL;
  if( __0_FuncPtr_ == NULL )
    __0_FuncPtr_ = (void *)( GetFunction( "@Slcommongen@TSLCommonIntGen@Pump$qqrv" ));

  VCLHANDLE __0_ThisPtr_ = Get_VCL_FunctionHandle();

  if( __0_FuncPtr_ && __0_ThisPtr_ )
    {
    _asm
      {
      push eax
      mov  eax,dword ptr [ __0_ThisPtr_ ]
      call dword ptr [ __0_FuncPtr_ ]
      pop  eax
      }
    }

}
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
inline CTSLCommonRealGen::CTSLCommonRealGen() :
  OutputPin( GetInstance(), _T( "OutputPin" ) )
{
  LibraryHandle = VCL_LoadLibrary( "SignalLabBasicPkgCB6.bpl" );
}
//------------------------------------------------------------------------------
inline TLPFunctionEntry CTSLCommonRealGen::GetFunction( const char *function_name )
{
  TLPFunctionEntry Result = VCL_GetFunction( LibraryHandle, function_name );
  if( Result )
    return Result;

  return inherited::GetFunction( function_name );
}
//------------------------------------------------------------------------------
inline void CTSLCommonRealGen::Pump()
{
  static void *__0_FuncPtr_ = NULL;
  if( __0_FuncPtr_ == NULL )
    __0_FuncPtr_ = (void *)( GetFunction( "@Slcommongen@TSLCommonRealGen@Pump$qqrv" ));

  VCLHANDLE __0_ThisPtr_ = Get_VCL_FunctionHandle();

  if( __0_FuncPtr_ && __0_ThisPtr_ )
    {
    _asm
      {
      push eax
      mov  eax,dword ptr [ __0_ThisPtr_ ]
      call dword ptr [ __0_FuncPtr_ ]
      pop  eax
      }
    }

}
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
#endif   // CSLCommonGenCode_H_
//------------------------------------------------------------------------------
