//------------------------------------------------------------------------------
//
//                    Generated by VCL C++ .NET FrontEnd.
//                   (C)Copyright Boian Mitov 2005 - 2009
//                              www.mitov.com
//
//------------------------------------------------------------------------------
#ifndef CSLCommonFilter_H_
#define CSLCommonFilter_H_

//------------------------------------------------------------------------------
#ifndef VCLSupportH
  #include <VCLSupport.h>
#endif

#ifndef CSignalLabBasicPkgCB6_H_
  #include <CSignalLabBasicPkgCB6.h>
#endif
#ifndef CSLStreamTypes_H_
  #include <CSLStreamTypes.h>
#endif


//------------------------------------------------------------------------------

enum CTSLMixerChannelWaitType { cwNone, cwStart };

//------------------------------------------------------------------------------
class CTSLBasicCommonFilter : public CLPComponent
{
//DOM-IGNORE-BEGIN
  typedef CLPComponent inherited;
//DOM-IGNORE-END

  VCLHANDLE LibraryHandle;

protected:
  virtual TLPFunctionEntry  GetFunction( const char *function_name );

public:    // Properties
  CLPProperty<bool> Enabled;

public:
  CTSLBasicCommonFilter();
};
//------------------------------------------------------------------------------
class CTSLCommonFilter : public CTSLBasicCommonFilter
{
//DOM-IGNORE-BEGIN
  typedef CTSLBasicCommonFilter inherited;
//DOM-IGNORE-END

  VCLHANDLE LibraryHandle;

protected:
  virtual TLPFunctionEntry  GetFunction( const char *function_name );

public:    // Properties
  CLPReadAccessProperty<CTSLCommonFilter,double> SampleRate;

protected:
  double GetVC_SampleRate();

public:
  CTSLCommonFilter();
};
//------------------------------------------------------------------------------
class CTSLCommonRealFilter : public CTSLCommonFilter
{
//DOM-IGNORE-BEGIN
  typedef CTSLCommonFilter inherited;
//DOM-IGNORE-END

  VCLHANDLE LibraryHandle;

protected:
  virtual TLPFunctionEntry  GetFunction( const char *function_name );

public:    // OpenWire Pins
  CTOWOutputPinProperty OutputPin;
  CTOWInputPinProperty InputPin;

public:
  CTSLCommonRealFilter();
};
//------------------------------------------------------------------------------
class CTSLCommonComplexFilter : public CTSLCommonFilter
{
//DOM-IGNORE-BEGIN
  typedef CTSLCommonFilter inherited;
//DOM-IGNORE-END

  VCLHANDLE LibraryHandle;

protected:
  virtual TLPFunctionEntry  GetFunction( const char *function_name );

public:    // OpenWire Pins
  CTOWOutputPinProperty OutputPin;
  CTOWInputPinProperty InputPin;

public:
  CTSLCommonComplexFilter();
};
//------------------------------------------------------------------------------
class CTSLCommonIntegerFilter : public CTSLCommonFilter
{
//DOM-IGNORE-BEGIN
  typedef CTSLCommonFilter inherited;
//DOM-IGNORE-END

  VCLHANDLE LibraryHandle;

protected:
  virtual TLPFunctionEntry  GetFunction( const char *function_name );

public:    // OpenWire Pins
  CTOWOutputPinProperty OutputPin;
  CTOWInputPinProperty InputPin;

public:
  CTSLCommonIntegerFilter();
};
//------------------------------------------------------------------------------
class CTSLCommonBinaryFilter : public CTSLCommonFilter
{
//DOM-IGNORE-BEGIN
  typedef CTSLCommonFilter inherited;
//DOM-IGNORE-END

  VCLHANDLE LibraryHandle;

protected:
  virtual TLPFunctionEntry  GetFunction( const char *function_name );

public:    // OpenWire Pins
  CTOWOutputPinProperty OutputPin;
  CTOWInputPinProperty InputPin;

public:
  CTSLCommonBinaryFilter();
};
//------------------------------------------------------------------------------
#include <CSLCommonFilterCode.h>
//------------------------------------------------------------------------------
#endif   // CSLCommonFilter_H_
//------------------------------------------------------------------------------
