//------------------------------------------------------------------------------
//
//                    Generated by VCL C++ .NET FrontEnd.
//                   (C)Copyright Boian Mitov 2005 - 2009
//                              www.mitov.com
//
//------------------------------------------------------------------------------
#ifndef CSLFilterTypesCode_H_
#define CSLFilterTypesCode_H_

//------------------------------------------------------------------------------
inline CTSLOffset::CTSLOffset( CLPBaseComponent *a_control, const CLPString a_PropertyName ) :
  inherited( a_control, a_PropertyName ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  CX( GetInstance(), _T( "CX" ) ),
  CY( GetInstance(), _T( "CY" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLOffset::CTSLOffset( CLPClassProperty *a_property, const CLPString a_PropertyName ) :
  inherited( a_property, a_PropertyName ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  CX( GetInstance(), _T( "CX" ) ),
  CY( GetInstance(), _T( "CY" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLOffset::CTSLOffset( CLPClassProperty *a_property, CTSLOffset ( CLPBaseClass::*a_getter )() ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(NULL),
  m_Owner_Property(a_property),
  CX( GetInstance(), _T( "CX" ) ),
  CY( GetInstance(), _T( "CY" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLOffset::CTSLOffset( CLPClassProperty *a_property, CTSLOffset ( CLPBaseClass::*a_getter )(), void ( CLPBaseClass::*a_setter )( CTSLOffset ) ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_property),
  CX( GetInstance(), _T( "CX" ) ),
  CY( GetInstance(), _T( "CY" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLOffset::CTSLOffset( CLPClassProperty *a_property, void ( CLPBaseClass::*a_setter )( CTSLOffset ) ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(NULL),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_property),
  CX( GetInstance(), _T( "CX" ) ),
  CY( GetInstance(), _T( "CY" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLOffset::CTSLOffset( CLPBaseComponent *a_control, CTSLOffset ( CLPBaseClass::*a_getter )() ) :
  inherited( a_control, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(NULL),
  m_Owner_Property(a_control),
  CX( GetInstance(), _T( "CX" ) ),
  CY( GetInstance(), _T( "CY" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLOffset::CTSLOffset( CLPBaseComponent *a_control, CTSLOffset ( CLPBaseClass::*a_getter )(), void ( CLPBaseClass::*a_setter )( CTSLOffset ) ) :
  inherited( a_control, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_control),
  CX( GetInstance(), _T( "CX" ) ),
  CY( GetInstance(), _T( "CY" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLOffset::CTSLOffset( VCLHANDLE handle, ELPHandleMode owns_handle ) :
  inherited( handle, owns_handle ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  CX( GetInstance(), _T( "CX" ) ),
  CY( GetInstance(), _T( "CY" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLOffset::CTSLOffset( const CTSLOffset &other ) :
  inherited( other ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  CX( GetInstance(), _T( "CX" ) ),
  CY( GetInstance(), _T( "CY" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLOffset & CTSLOffset::operator = ( const CTSLOffset & other )
{
  if( m_Property_Setter )
	  (m_Owner_Property->*m_Property_Setter)( other );

  else
	  inherited::operator = ( other );

  return *this;
}
//------------------------------------------------------------------------------
inline VCLHANDLE CTSLOffset::Get_VCL_Handle() const
{
  if( m_Property_Getter )
	  {
		if( ! m_Object )
		  m_Object = new CVCLObject( (m_Owner_Property->*m_Property_Getter)().Get_VCL_Handle() );

	  }

  return inherited::Get_VCL_Handle();
}
//------------------------------------------------------------------------------
inline CTSLDelayValue::CTSLDelayValue( CLPBaseComponent *a_control, const CLPString a_PropertyName ) :
  inherited( a_control, a_PropertyName ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  Value( GetInstance(), _T( "Value" ) ),
  Mode( GetInstance(), _T( "Mode" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLDelayValue::CTSLDelayValue( CLPClassProperty *a_property, const CLPString a_PropertyName ) :
  inherited( a_property, a_PropertyName ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  Value( GetInstance(), _T( "Value" ) ),
  Mode( GetInstance(), _T( "Mode" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLDelayValue::CTSLDelayValue( CLPClassProperty *a_property, CTSLDelayValue ( CLPBaseClass::*a_getter )() ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(NULL),
  m_Owner_Property(a_property),
  Value( GetInstance(), _T( "Value" ) ),
  Mode( GetInstance(), _T( "Mode" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLDelayValue::CTSLDelayValue( CLPClassProperty *a_property, CTSLDelayValue ( CLPBaseClass::*a_getter )(), void ( CLPBaseClass::*a_setter )( CTSLDelayValue ) ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_property),
  Value( GetInstance(), _T( "Value" ) ),
  Mode( GetInstance(), _T( "Mode" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLDelayValue::CTSLDelayValue( CLPClassProperty *a_property, void ( CLPBaseClass::*a_setter )( CTSLDelayValue ) ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(NULL),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_property),
  Value( GetInstance(), _T( "Value" ) ),
  Mode( GetInstance(), _T( "Mode" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLDelayValue::CTSLDelayValue( CLPBaseComponent *a_control, CTSLDelayValue ( CLPBaseClass::*a_getter )() ) :
  inherited( a_control, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(NULL),
  m_Owner_Property(a_control),
  Value( GetInstance(), _T( "Value" ) ),
  Mode( GetInstance(), _T( "Mode" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLDelayValue::CTSLDelayValue( CLPBaseComponent *a_control, CTSLDelayValue ( CLPBaseClass::*a_getter )(), void ( CLPBaseClass::*a_setter )( CTSLDelayValue ) ) :
  inherited( a_control, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_control),
  Value( GetInstance(), _T( "Value" ) ),
  Mode( GetInstance(), _T( "Mode" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLDelayValue::CTSLDelayValue( VCLHANDLE handle, ELPHandleMode owns_handle ) :
  inherited( handle, owns_handle ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  Value( GetInstance(), _T( "Value" ) ),
  Mode( GetInstance(), _T( "Mode" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLDelayValue::CTSLDelayValue( const CTSLDelayValue &other ) :
  inherited( other ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  Value( GetInstance(), _T( "Value" ) ),
  Mode( GetInstance(), _T( "Mode" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLDelayValue & CTSLDelayValue::operator = ( const CTSLDelayValue & other )
{
  if( m_Property_Setter )
	  (m_Owner_Property->*m_Property_Setter)( other );

  else
	  inherited::operator = ( other );

  return *this;
}
//------------------------------------------------------------------------------
inline VCLHANDLE CTSLDelayValue::Get_VCL_Handle() const
{
  if( m_Property_Getter )
	  {
		if( ! m_Object )
		  m_Object = new CVCLObject( (m_Owner_Property->*m_Property_Getter)().Get_VCL_Handle() );

	  }

  return inherited::Get_VCL_Handle();
}
//------------------------------------------------------------------------------
inline CTSLCoordinateOffset::CTSLCoordinateOffset( CLPBaseComponent *a_control, const CLPString a_PropertyName ) :
  inherited( a_control, a_PropertyName ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  CoordinateMode( GetInstance(), _T( "CoordinateMode" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLCoordinateOffset::CTSLCoordinateOffset( CLPClassProperty *a_property, const CLPString a_PropertyName ) :
  inherited( a_property, a_PropertyName ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  CoordinateMode( GetInstance(), _T( "CoordinateMode" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLCoordinateOffset::CTSLCoordinateOffset( CLPClassProperty *a_property, CTSLCoordinateOffset ( CLPBaseClass::*a_getter )() ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(NULL),
  m_Owner_Property(a_property),
  CoordinateMode( GetInstance(), _T( "CoordinateMode" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLCoordinateOffset::CTSLCoordinateOffset( CLPClassProperty *a_property, CTSLCoordinateOffset ( CLPBaseClass::*a_getter )(), void ( CLPBaseClass::*a_setter )( CTSLCoordinateOffset ) ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_property),
  CoordinateMode( GetInstance(), _T( "CoordinateMode" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLCoordinateOffset::CTSLCoordinateOffset( CLPClassProperty *a_property, void ( CLPBaseClass::*a_setter )( CTSLCoordinateOffset ) ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(NULL),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_property),
  CoordinateMode( GetInstance(), _T( "CoordinateMode" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLCoordinateOffset::CTSLCoordinateOffset( CLPBaseComponent *a_control, CTSLCoordinateOffset ( CLPBaseClass::*a_getter )() ) :
  inherited( a_control, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(NULL),
  m_Owner_Property(a_control),
  CoordinateMode( GetInstance(), _T( "CoordinateMode" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLCoordinateOffset::CTSLCoordinateOffset( CLPBaseComponent *a_control, CTSLCoordinateOffset ( CLPBaseClass::*a_getter )(), void ( CLPBaseClass::*a_setter )( CTSLCoordinateOffset ) ) :
  inherited( a_control, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_control),
  CoordinateMode( GetInstance(), _T( "CoordinateMode" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLCoordinateOffset::CTSLCoordinateOffset( VCLHANDLE handle, ELPHandleMode owns_handle ) :
  inherited( handle, owns_handle ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  CoordinateMode( GetInstance(), _T( "CoordinateMode" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLCoordinateOffset::CTSLCoordinateOffset( const CTSLCoordinateOffset &other ) :
  inherited( other ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  CoordinateMode( GetInstance(), _T( "CoordinateMode" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLCoordinateOffset & CTSLCoordinateOffset::operator = ( const CTSLCoordinateOffset & other )
{
  if( m_Property_Setter )
	  (m_Owner_Property->*m_Property_Setter)( other );

  else
	  inherited::operator = ( other );

  return *this;
}
//------------------------------------------------------------------------------
inline VCLHANDLE CTSLCoordinateOffset::Get_VCL_Handle() const
{
  if( m_Property_Getter )
	  {
		if( ! m_Object )
		  m_Object = new CVCLObject( (m_Owner_Property->*m_Property_Getter)().Get_VCL_Handle() );

	  }

  return inherited::Get_VCL_Handle();
}
//------------------------------------------------------------------------------
inline CTSLDisplayBrush::CTSLDisplayBrush( CLPBaseComponent *a_control, const CLPString a_PropertyName ) :
  inherited( a_control, a_PropertyName ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  Color( (CTSLDisplayBrush *)GetInstance(), &CTSLDisplayBrush::GetColor, &CTSLDisplayBrush::SetColor),
  Style( (CTSLDisplayBrush *)GetInstance(), &CTSLDisplayBrush::GetStyle, &CTSLDisplayBrush::SetStyle)
{
}
//------------------------------------------------------------------------------
inline CTSLDisplayBrush::CTSLDisplayBrush( CLPClassProperty *a_property, const CLPString a_PropertyName ) :
  inherited( a_property, a_PropertyName ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  Color( (CTSLDisplayBrush *)GetInstance(), &CTSLDisplayBrush::GetColor, &CTSLDisplayBrush::SetColor),
  Style( (CTSLDisplayBrush *)GetInstance(), &CTSLDisplayBrush::GetStyle, &CTSLDisplayBrush::SetStyle)
{
}
//------------------------------------------------------------------------------
inline CTSLDisplayBrush::CTSLDisplayBrush( CLPClassProperty *a_property, CTSLDisplayBrush ( CLPBaseClass::*a_getter )() ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(NULL),
  m_Owner_Property(a_property),
  Color( (CTSLDisplayBrush *)GetInstance(), &CTSLDisplayBrush::GetColor, &CTSLDisplayBrush::SetColor),
  Style( (CTSLDisplayBrush *)GetInstance(), &CTSLDisplayBrush::GetStyle, &CTSLDisplayBrush::SetStyle)
{
}
//------------------------------------------------------------------------------
inline CTSLDisplayBrush::CTSLDisplayBrush( CLPClassProperty *a_property, CTSLDisplayBrush ( CLPBaseClass::*a_getter )(), void ( CLPBaseClass::*a_setter )( CTSLDisplayBrush ) ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_property),
  Color( (CTSLDisplayBrush *)GetInstance(), &CTSLDisplayBrush::GetColor, &CTSLDisplayBrush::SetColor),
  Style( (CTSLDisplayBrush *)GetInstance(), &CTSLDisplayBrush::GetStyle, &CTSLDisplayBrush::SetStyle)
{
}
//------------------------------------------------------------------------------
inline CTSLDisplayBrush::CTSLDisplayBrush( CLPClassProperty *a_property, void ( CLPBaseClass::*a_setter )( CTSLDisplayBrush ) ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(NULL),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_property),
  Color( (CTSLDisplayBrush *)GetInstance(), &CTSLDisplayBrush::GetColor, &CTSLDisplayBrush::SetColor),
  Style( (CTSLDisplayBrush *)GetInstance(), &CTSLDisplayBrush::GetStyle, &CTSLDisplayBrush::SetStyle)
{
}
//------------------------------------------------------------------------------
inline CTSLDisplayBrush::CTSLDisplayBrush( CLPBaseComponent *a_control, CTSLDisplayBrush ( CLPBaseClass::*a_getter )() ) :
  inherited( a_control, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(NULL),
  m_Owner_Property(a_control),
  Color( (CTSLDisplayBrush *)GetInstance(), &CTSLDisplayBrush::GetColor, &CTSLDisplayBrush::SetColor),
  Style( (CTSLDisplayBrush *)GetInstance(), &CTSLDisplayBrush::GetStyle, &CTSLDisplayBrush::SetStyle)
{
}
//------------------------------------------------------------------------------
inline CTSLDisplayBrush::CTSLDisplayBrush( CLPBaseComponent *a_control, CTSLDisplayBrush ( CLPBaseClass::*a_getter )(), void ( CLPBaseClass::*a_setter )( CTSLDisplayBrush ) ) :
  inherited( a_control, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_control),
  Color( (CTSLDisplayBrush *)GetInstance(), &CTSLDisplayBrush::GetColor, &CTSLDisplayBrush::SetColor),
  Style( (CTSLDisplayBrush *)GetInstance(), &CTSLDisplayBrush::GetStyle, &CTSLDisplayBrush::SetStyle)
{
}
//------------------------------------------------------------------------------
inline CTSLDisplayBrush::CTSLDisplayBrush( VCLHANDLE handle, ELPHandleMode owns_handle ) :
  inherited( handle, owns_handle ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  Color( (CTSLDisplayBrush *)GetInstance(), &CTSLDisplayBrush::GetColor, &CTSLDisplayBrush::SetColor),
  Style( (CTSLDisplayBrush *)GetInstance(), &CTSLDisplayBrush::GetStyle, &CTSLDisplayBrush::SetStyle)
{
}
//------------------------------------------------------------------------------
inline CTSLDisplayBrush::CTSLDisplayBrush( const CTSLDisplayBrush &other ) :
  inherited( other ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  Color( (CTSLDisplayBrush *)GetInstance(), &CTSLDisplayBrush::GetColor, &CTSLDisplayBrush::SetColor),
  Style( (CTSLDisplayBrush *)GetInstance(), &CTSLDisplayBrush::GetStyle, &CTSLDisplayBrush::SetStyle)
{
}
//------------------------------------------------------------------------------
inline CTSLDisplayBrush & CTSLDisplayBrush::operator = ( const CTSLDisplayBrush & other )
{
  if( m_Property_Setter )
	  (m_Owner_Property->*m_Property_Setter)( other );

  else
	  inherited::operator = ( other );

  return *this;
}
//------------------------------------------------------------------------------
inline VCLHANDLE CTSLDisplayBrush::Get_VCL_Handle() const
{
  if( m_Property_Getter )
	  {
		if( ! m_Object )
		  m_Object = new CVCLObject( (m_Owner_Property->*m_Property_Getter)().Get_VCL_Handle() );

	  }

  return inherited::Get_VCL_Handle();
}
//------------------------------------------------------------------------------
inline unsigned char CTSLDisplayBrush::GetStyle()
{
  static void *__0_FuncPtr_ = NULL;
  if( __0_FuncPtr_ == NULL )
    __0_FuncPtr_ = (void *)( GetFunction( "@Slfiltertypes@TSLDisplayBrush@GetStyle$qqrv" ));

  VCLHANDLE __0_ThisPtr_ = Get_VCL_FunctionHandle();

  unsigned char __0_RtnValue_ = 0;

  if( __0_FuncPtr_ && __0_ThisPtr_ )
    {
    _asm
      {
      push eax
      mov  eax,dword ptr [ __0_ThisPtr_ ]
      call dword ptr [ __0_FuncPtr_ ]
      mov  __0_RtnValue_,al
      pop  eax
      }
    }

  return (unsigned char)__0_RtnValue_;
}
//------------------------------------------------------------------------------
inline void CTSLDisplayBrush::SetStyle( unsigned char Value )
{
  static void *__0_FuncPtr_ = NULL;
  if( __0_FuncPtr_ == NULL )
    __0_FuncPtr_ = (void *)( GetFunction( "@Slfiltertypes@TSLDisplayBrush@SetStyle$qqr20Graphics@TBrushStyle" ));

  VCLHANDLE __0_ThisPtr_ = Get_VCL_FunctionHandle();

  if( __0_FuncPtr_ && __0_ThisPtr_ )
    {
    unsigned char __1_Param1 = Value;

    _asm
      {
      push eax
      push edx
      mov  edx,0
      mov  dl,__1_Param1
      mov  eax,dword ptr [ __0_ThisPtr_ ]
      call dword ptr [ __0_FuncPtr_ ]
      pop  edx
      pop  eax
      }
    }

}
//------------------------------------------------------------------------------
inline CTColor CTSLDisplayBrush::GetColor()
{
  static void *__0_FuncPtr_ = NULL;
  if( __0_FuncPtr_ == NULL )
    __0_FuncPtr_ = (void *)( GetFunction( "@Slfiltertypes@TSLDisplayBrush@GetColor$qqrv" ));

  VCLHANDLE __0_ThisPtr_ = Get_VCL_FunctionHandle();

  CTColor __0_RtnValue_ = (CTColor)0;

  if( __0_FuncPtr_ && __0_ThisPtr_ )
    {
    _asm
      {
      push eax
      mov  eax,dword ptr [ __0_ThisPtr_ ]
      call dword ptr [ __0_FuncPtr_ ]
      mov  __0_RtnValue_,eax
      pop  eax
      }
    }

  return (CTColor)__0_RtnValue_;
}
//------------------------------------------------------------------------------
inline void CTSLDisplayBrush::SetColor( CTColor Value )
{
  static void *__0_FuncPtr_ = NULL;
  if( __0_FuncPtr_ == NULL )
    __0_FuncPtr_ = (void *)( GetFunction( "@Slfiltertypes@TSLDisplayBrush@SetColor$qqr15Graphics@TColor" ));

  VCLHANDLE __0_ThisPtr_ = Get_VCL_FunctionHandle();

  if( __0_FuncPtr_ && __0_ThisPtr_ )
    {
    CTColor __1_Param1 = Value;

    _asm
      {
      push eax
      push edx
      mov  edx,__1_Param1
      mov  eax,dword ptr [ __0_ThisPtr_ ]
      call dword ptr [ __0_FuncPtr_ ]
      pop  edx
      pop  eax
      }
    }

}
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
inline CTSLBasicOptionalLabel::CTSLBasicOptionalLabel( CLPBaseComponent *a_control, const CLPString a_PropertyName ) :
  inherited( a_control, a_PropertyName ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  Font( *new CTFont( GetInstance(), _T( "Font" ))),
  Visible( GetInstance(), _T( "Visible" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLBasicOptionalLabel::CTSLBasicOptionalLabel( CLPClassProperty *a_property, const CLPString a_PropertyName ) :
  inherited( a_property, a_PropertyName ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  Font( *new CTFont( GetInstance(), _T( "Font" ))),
  Visible( GetInstance(), _T( "Visible" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLBasicOptionalLabel::CTSLBasicOptionalLabel( CLPClassProperty *a_property, CTSLBasicOptionalLabel ( CLPBaseClass::*a_getter )() ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(NULL),
  m_Owner_Property(a_property),
  Font( *new CTFont( GetInstance(), _T( "Font" ))),
  Visible( GetInstance(), _T( "Visible" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLBasicOptionalLabel::CTSLBasicOptionalLabel( CLPClassProperty *a_property, CTSLBasicOptionalLabel ( CLPBaseClass::*a_getter )(), void ( CLPBaseClass::*a_setter )( CTSLBasicOptionalLabel ) ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_property),
  Font( *new CTFont( GetInstance(), _T( "Font" ))),
  Visible( GetInstance(), _T( "Visible" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLBasicOptionalLabel::CTSLBasicOptionalLabel( CLPClassProperty *a_property, void ( CLPBaseClass::*a_setter )( CTSLBasicOptionalLabel ) ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(NULL),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_property),
  Font( *new CTFont( GetInstance(), _T( "Font" ))),
  Visible( GetInstance(), _T( "Visible" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLBasicOptionalLabel::CTSLBasicOptionalLabel( CLPBaseComponent *a_control, CTSLBasicOptionalLabel ( CLPBaseClass::*a_getter )() ) :
  inherited( a_control, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(NULL),
  m_Owner_Property(a_control),
  Font( *new CTFont( GetInstance(), _T( "Font" ))),
  Visible( GetInstance(), _T( "Visible" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLBasicOptionalLabel::CTSLBasicOptionalLabel( CLPBaseComponent *a_control, CTSLBasicOptionalLabel ( CLPBaseClass::*a_getter )(), void ( CLPBaseClass::*a_setter )( CTSLBasicOptionalLabel ) ) :
  inherited( a_control, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_control),
  Font( *new CTFont( GetInstance(), _T( "Font" ))),
  Visible( GetInstance(), _T( "Visible" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLBasicOptionalLabel::CTSLBasicOptionalLabel( VCLHANDLE handle, ELPHandleMode owns_handle ) :
  inherited( handle, owns_handle ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  Font( *new CTFont( GetInstance(), _T( "Font" ))),
  Visible( GetInstance(), _T( "Visible" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLBasicOptionalLabel::CTSLBasicOptionalLabel( const CTSLBasicOptionalLabel &other ) :
  inherited( other ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  Font( *new CTFont( GetInstance(), _T( "Font" ))),
  Visible( GetInstance(), _T( "Visible" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLBasicOptionalLabel::~CTSLBasicOptionalLabel()
{
  delete &Font;
}
//------------------------------------------------------------------------------
inline CTSLBasicOptionalLabel & CTSLBasicOptionalLabel::operator = ( const CTSLBasicOptionalLabel & other )
{
  if( m_Property_Setter )
	  (m_Owner_Property->*m_Property_Setter)( other );

  else
	  inherited::operator = ( other );

  return *this;
}
//------------------------------------------------------------------------------
inline VCLHANDLE CTSLBasicOptionalLabel::Get_VCL_Handle() const
{
  if( m_Property_Getter )
	  {
		if( ! m_Object )
		  m_Object = new CVCLObject( (m_Owner_Property->*m_Property_Getter)().Get_VCL_Handle() );

	  }

  return inherited::Get_VCL_Handle();
}
//------------------------------------------------------------------------------
inline CTSLOptionalLabel::CTSLOptionalLabel( CLPBaseComponent *a_control, const CLPString a_PropertyName ) :
  inherited( a_control, a_PropertyName ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  Text( GetInstance(), _T( "Text" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLOptionalLabel::CTSLOptionalLabel( CLPClassProperty *a_property, const CLPString a_PropertyName ) :
  inherited( a_property, a_PropertyName ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  Text( GetInstance(), _T( "Text" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLOptionalLabel::CTSLOptionalLabel( CLPClassProperty *a_property, CTSLOptionalLabel ( CLPBaseClass::*a_getter )() ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(NULL),
  m_Owner_Property(a_property),
  Text( GetInstance(), _T( "Text" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLOptionalLabel::CTSLOptionalLabel( CLPClassProperty *a_property, CTSLOptionalLabel ( CLPBaseClass::*a_getter )(), void ( CLPBaseClass::*a_setter )( CTSLOptionalLabel ) ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_property),
  Text( GetInstance(), _T( "Text" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLOptionalLabel::CTSLOptionalLabel( CLPClassProperty *a_property, void ( CLPBaseClass::*a_setter )( CTSLOptionalLabel ) ) :
  inherited( a_property, _T( "-" ) ),
  m_Property_Getter(NULL),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_property),
  Text( GetInstance(), _T( "Text" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLOptionalLabel::CTSLOptionalLabel( CLPBaseComponent *a_control, CTSLOptionalLabel ( CLPBaseClass::*a_getter )() ) :
  inherited( a_control, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(NULL),
  m_Owner_Property(a_control),
  Text( GetInstance(), _T( "Text" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLOptionalLabel::CTSLOptionalLabel( CLPBaseComponent *a_control, CTSLOptionalLabel ( CLPBaseClass::*a_getter )(), void ( CLPBaseClass::*a_setter )( CTSLOptionalLabel ) ) :
  inherited( a_control, _T( "-" ) ),
  m_Property_Getter(a_getter),
  m_Property_Setter(a_setter),
  m_Owner_Property(a_control),
  Text( GetInstance(), _T( "Text" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLOptionalLabel::CTSLOptionalLabel( VCLHANDLE handle, ELPHandleMode owns_handle ) :
  inherited( handle, owns_handle ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  Text( GetInstance(), _T( "Text" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLOptionalLabel::CTSLOptionalLabel( const CTSLOptionalLabel &other ) :
  inherited( other ),
  m_Property_Getter( NULL ),
  m_Property_Setter( NULL ),
  m_Owner_Property( NULL ),
  Text( GetInstance(), _T( "Text" ) )
{
}
//------------------------------------------------------------------------------
inline CTSLOptionalLabel & CTSLOptionalLabel::operator = ( const CTSLOptionalLabel & other )
{
  if( m_Property_Setter )
	  (m_Owner_Property->*m_Property_Setter)( other );

  else
	  inherited::operator = ( other );

  return *this;
}
//------------------------------------------------------------------------------
inline VCLHANDLE CTSLOptionalLabel::Get_VCL_Handle() const
{
  if( m_Property_Getter )
	  {
		if( ! m_Object )
		  m_Object = new CVCLObject( (m_Owner_Property->*m_Property_Getter)().Get_VCL_Handle() );

	  }

  return inherited::Get_VCL_Handle();
}
//------------------------------------------------------------------------------
#endif   // CSLFilterTypesCode_H_
//------------------------------------------------------------------------------
