//------------------------------------------------------------------------------
//
//                    Generated by VCL C++ .NET FrontEnd.
//                   (C)Copyright Boian Mitov 2005 - 2009
//                              www.mitov.com
//
//------------------------------------------------------------------------------
#ifndef CSLGenericFilterTypes_H_
#define CSLGenericFilterTypes_H_

//------------------------------------------------------------------------------
#ifndef VCLSupportH
  #include <VCLSupport.h>
#endif

#ifndef CSignalLabBasicPkgCB6_H_
  #include <CSignalLabBasicPkgCB6.h>
#endif


//------------------------------------------------------------------------------


//------------------------------------------------------------------------------
#include <CSLGenericFilterTypesCode.h>
//------------------------------------------------------------------------------
#endif   // CSLGenericFilterTypes_H_
//------------------------------------------------------------------------------
