//------------------------------------------------------------------------------
//
//                    Generated by VCL C++ .NET FrontEnd.
//                   (C)Copyright Boian Mitov 2005 - 2009
//                              www.mitov.com
//
//------------------------------------------------------------------------------
#ifndef CSLSyncTypes_H_
#define CSLSyncTypes_H_

//------------------------------------------------------------------------------
#ifndef VCLSupportH
  #include <VCLSupport.h>
#endif

#ifndef CSignalLabBasicPkgCB6_H_
  #include <CSignalLabBasicPkgCB6.h>
#endif


//------------------------------------------------------------------------------

enum CTSLSynchronizeType { stNone, stSingleBuffer, stQueue };

//------------------------------------------------------------------------------
#include <CSLSyncTypesCode.h>
//------------------------------------------------------------------------------
#endif   // CSLSyncTypes_H_
//------------------------------------------------------------------------------
